// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertSlots implements pgx.CopyFromSource.
type iteratorForInsertSlots struct {
	rows                 []InsertSlotsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSlots) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSlots) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DoctorID,
		r.rows[0].StartTime,
	}, nil
}

func (r iteratorForInsertSlots) Err() error {
	return nil
}

func (q *Queries) InsertSlots(ctx context.Context, arg []InsertSlotsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"slot"}, []string{"doctor_id", "start_time"}, &iteratorForInsertSlots{rows: arg})
}
