// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID        int32
	PatientID pgtype.Int4
	Note      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Doctor struct {
	ID             int32
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Patient struct {
	ID             int32
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Slot struct {
	ID        int32
	DoctorID  pgtype.Int4
	StartTime pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Available pgtype.Bool
}
