// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: slot.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type InsertSlotsParams struct {
	DoctorID  pgtype.Int4
	StartTime pgtype.Timestamp
}

const updateSlotAvailability = `-- name: UpdateSlotAvailability :exec
UPDATE slot
SET
  available = $2
WHERE
  id = $1
`

type UpdateSlotAvailabilityParams struct {
	ID        int32
	Available pgtype.Bool
}

func (q *Queries) UpdateSlotAvailability(ctx context.Context, arg UpdateSlotAvailabilityParams) error {
	_, err := q.db.Exec(ctx, updateSlotAvailability, arg.ID, arg.Available)
	return err
}
